# Partly based on https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
# which is (c) GitLab B.V. and published under the MIT Licence linked here: https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE

workflow:
  rules:
    # - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"

# include:
#   - template: Jobs/SAST.gitlab-ci.yml

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  # - test
  - deploy

default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:latest

  # https://pip.pypa.io/en/stable/topics/caching/
  cache:
    paths:
      - .cache/pip

  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate

build:
  stage: build
  script:
    - python -m pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*
  interruptible: true
  rules:
    # - if: $CI_COMMIT_TAG
    #   when: on_success
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success

publish:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  script:
    # Adapted from https://docs.pypi.org/trusted-publishers/using-a-publisher/
    # Install dependencies
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade twine

    # Upload to GitLab Package Registry
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi --username gitlab-ci-token --password ${CI_JOB_TOKEN} --verbose dist/*

    # Upload to Python Package Index
    # With no token specified, twine will use Trusted Publishing
    - python -m twine upload --repository-url https://upload.pypi.org/legacy/ --skip-existing --verbose dist/*
  interruptible: false
  when: manual
  manual_confirmation: "Publish new version to Python Package Index and GitLab Package Registry?"

docs:
  stage: deploy
  needs: []
  script:
    - python -m pip install sphinx aiohttp aiolimiter ratelimit requests tzdata  # need to import third-party libraries used by project
    - cd docs
    - sphinx-build -n --color source build
  pages:
    publish: docs/build
  interruptible: true
  when: manual
  manual_confirmation: "Update docs?"
