# Partly based on https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
# which is (c) GitLab B.V. and published under the MIT Licence linked here: https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE

# include:
#   - template: Jobs/SAST.gitlab-ci.yml

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  # - test
  - deploy

default:
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:latest

  # https://pip.pypa.io/en/stable/topics/caching/
  cache:
    paths:
      - .cache/pip

  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate

build:
  stage: build
  script:
    - python -m pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*
  interruptible: true
  when: manual

publish:
  stage: deploy
  dependencies:
    - build
  script:
    # Adapted from https://bitwarden.com/help/gitlab-integration/
    - |
      # install bws
      apt-get update && apt-get install -y curl git jq unzip
      export BWS_VER="1.0.0"
      curl -LO "https://github.com/bitwarden/sdk/releases/download/bws-v$BWS_VER/bws-x86_64-unknown-linux-gnu-$BWS_VER.zip"
      unzip -o bws-x86_64-unknown-linux-gnu-$BWS_VER.zip -d /usr/local/bin
      
      # secret to retrieve
      secret_id="8b87c7dd-20fe-462f-b29c-b1e200e8c148"
      
      # export secret as environment variable
      secret="$(bws secret get "$secret_id")"
      export PYPI_TOKEN="$(echo "$secret" | jq -r '.value')"

    - python -m pip install twine
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi --username gitlab-ci-token --password ${CI_JOB_TOKEN} --skip-existing --verbose dist/*  # upload to GitLab Package Registry
    - python -m twine upload --repository-url https://upload.pypi.org/legacy/ --username __token__ --password ${PYPI_TOKEN} --skip-existing --verbose dist/*  # upload to Python Package Index
  interruptible: false
  when: manual
  manual_confirmation: "Publish new version to Python Package Index and GitLab Package Registry?"
